services:
  # PostgreSQL Database for User Service
  siska-user-db:
    container_name: siska-user-db-pgsql
    image: postgres
    environment:
      POSTGRES_DB: siska_user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - siskauserdb-data:/var/lib/postgresql/data\

  # User Service
  user-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://siska-user-db:5432/siska_user
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - siska-user-db

volumes:
  siskauserdb-data: